[package]
name = "bingorat"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
ratatui = { version = "0.30.0", features = ["macros"] }

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }

module_name_repetitions = "allow"
missing_err_doc = "allow"
missing_panics_doc = "allow"
